//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Auth.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class FormRoleMapping
    {
        public int Id { get; set; }
        [DisplayName("Form ID")]
        public Nullable<int> FormID { get; set; }
        [DisplayName("Role ID")]
        public Nullable<int> RoleID { get; set; }
        [DisplayName("Create")]
        public Nullable<bool> AllowInsert { get; set; }
        [DisplayName("Edit")]
        public Nullable<bool> AllowEdit { get; set; }
        [DisplayName("Delete")]
        public Nullable<bool> AllowDelete { get; set; }
        [DisplayName("View")]
        public Nullable<bool> AllowView { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
