//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Auth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormMaster
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string NavigateURL { get; set; }
        public string ParentFormId { get; set; }
        public string FormAccessCode { get; set; }
        public string DisplayOrder { get; set; }
        public Nullable<bool> IsDisplayMenu { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
