//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Auth.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Purchase
    {
        public int id { get; set; }
        public string Purchase_Product { get; set; }
        public string Purchase_Quntity { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime Purchase_date { get; set; }
    }
}
